name: 'IronSpec: Governance Guard'
description: 'The "Iron Dome" for AI-Native Dev Shops.'
inputs:
  gemini_api_key:
    description: 'Gemini API Key'
    required: false
  # 👇 1. Must define the input here
  openai_api_key:
    description: 'OpenAI API Key'
    required: false
  linear_api_key:
    description: 'API Key for Audit Logging'
    required: true
  notion_api_key:
    description: 'API Key for fetching Specs'
    required: true
  github_token:
    description: 'GITHUB_TOKEN'
    required: true
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install Dependencies
      shell: bash
      run: pip install -r ${{ github.action_path }}/requirements.txt
    - name: Run Governance Guard
      shell: bash
      env:
        GEMINI_API_KEY: ${{ inputs.gemini_api_key }}
        # 👇 2. Must pass the input to environment variable here
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        LINEAR_API_KEY: ${{ inputs.linear_api_key }}
        NOTION_TOKEN: ${{ inputs.notion_api_key }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_EVENT_PATH: ${{ github.event_path }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_REF: ${{ github.ref }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
      run: python ${{ github.action_path }}/.github/scripts/action-guard.py
